### ISSUE TITLE
API Methods creation progress

### ISSUE THREAD

**Issue by dotX12** [dotX12/Shazam#1]
- [x]  - SEARCH_FROM_FILE

- [x] TOP_WORLD

- [x]  - ABOUT_ARTIST

- [x]  - ARTIST_TOP_TRACKS

- [x]  - ABOUT_TRACK

- [x]  - TOP_TRACKS_COUNTRY

- [x] - TOP_TRACKS_CITY

- [x]  - CITY_ID

- [x]  - GENRE_WORLD

- [x]  - GENRE_COUNTRY

**Comment by dotX12** [comment]
- [✅]  - TOP_WORLD

- [✅]  - ABOUT_ARTIST

- [✅]  - ARTIST_TOP_TRACKS

**Comment by dotX12** [comment]
Close issue. All methods created.

**Comment by cottongin** [comment]
Not sure if this is the place to ask but a `from_bytes` or something similar would be helpful.

I tried passing my object in but it appears to be expecting paths only:
https://github.com/dotX12/ShazamIO/blob/master/shazamio/utils.py#L18
